var annotated_dup =
[
    [ "BBUInfo", "struct_b_b_u_info.html", null ],
    [ "CMOS_BAT_INFO", "struct_c_m_o_s___b_a_t___i_n_f_o.html", null ],
    [ "CPUInfo", "struct_c_p_u_info.html", null ],
    [ "CpuUsage", "struct_cpu_usage.html", null ],
    [ "DateInfo", "struct_date_info.html", null ],
    [ "DiskInfo", "struct_disk_info.html", null ],
    [ "DockerInfo", "struct_docker_info.html", null ],
    [ "FANInfo", "struct_f_a_n_info.html", null ],
    [ "FileInfo", "struct_file_info.html", null ],
    [ "HBAInfo", "struct_h_b_a_info.html", null ],
    [ "IFASpeed", "struct_i_f_a_speed.html", null ],
    [ "LoginInfo", "struct_login_info.html", null ],
    [ "MEM_UNIT_INFO", "struct_m_e_m___u_n_i_t___i_n_f_o.html", null ],
    [ "MEMInfo", "struct_m_e_m_info.html", null ],
    [ "MemUsage", "struct_mem_usage.html", null ],
    [ "MenuItem", "struct_menu_item.html", null ],
    [ "PartitionInfo", "struct_partition_info.html", null ],
    [ "PHYSICAL_IFA_Info", "struct_p_h_y_s_i_c_a_l___i_f_a___info.html", null ],
    [ "ProcessInfo", "struct_process_info.html", null ],
    [ "SystemInfo", "struct_system_info.html", null ],
    [ "TempInfo", "struct_temp_info.html", null ],
    [ "TempLog", "struct_temp_log.html", null ],
    [ "Unit_Mapping", "struct_unit___mapping.html", null ],
    [ "UsageLog", "struct_usage_log.html", null ],
    [ "UserInfo", "struct_user_info.html", null ],
    [ "VDInfo", "struct_v_d_info.html", null ],
    [ "WarningLog", "struct_warning_log.html", null ]
];